LOCAL_PATH := $(my-dir)
include $(CLEAR_VARS)

LOCAL_SHARED_LIBRARIES := libcutils liblog

LOCAL_CFLAGS  += -DQEMU_HARDWARE -std=c99
QEMU_HARDWARE := true

LOCAL_SRC_FILES += test_pwm.c \


LOCAL_MODULE:= testpwm
LOCAL_MODULE_PATH := $(TARGET_OUT_EXECUTABLES)

include $(BUILD_EXECUTABLE)
